import Header from '@/components/Header';
import Footer from '@/components/Footer';
import './globals.css';


export const metadata = {
  title: 'CI/CD Project',
  description: 'Generated by Next.js and Antigravity',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body suppressHydrationWarning>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
