import './globals.css';

export const metadata = {
  title: 'CI/CD Project',
  description: 'Generated by Next.js and Antigravity',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
